const screens=['login','create','home','servers','settings','game'];
const $=id=>document.getElementById(id);
function show(name){screens.forEach(s=>$(s).classList.toggle('hidden',s!==name)); if(name==='game') startGame();}
let username=localStorage.getItem('rw_user')||'';
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return; if(a==='create')show('create'); if(a==='back-login')show('login'); if(a==='login'||a==='guest'){if(a==='guest')username='Guest';show('home')} if(a==='create-submit'){username=$('newUser').value.trim()||'Survivor';localStorage.setItem('rw_user',username);show('home')} if(a==='play')show('game');if(a==='servers')show('servers');if(a==='settings')show('settings');if(a==='home')show('home');if(a==='map')$('mapOverlay').classList.toggle('hidden');if(a==='inventory')$('inventory').classList.toggle('hidden');if(a==='quit')show('login');if(a==='focus-user'){}if(a==='focus-pass'){} });
const items=['Rock','Torch','Hunting Bow','Compound Bow','Crossbow','Eoka Pistol','Revolver','Thompson','MP5A4','SAR','Bolt Action Rifle','Assault Rifle','Machete','Bone Knife','Hatchet','Pickaxe','Paddle','Chainsaw'];
let selected=0;
function buildInv(){const s=$('slots');s.innerHTML='';items.forEach((it,i)=>{const b=document.createElement('button');b.className='slot'+(i===selected?' selected':'');b.textContent=it;b.onclick=()=>{selected=i;document.querySelectorAll('.slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('selected').textContent='Selected: '+items[selected]};s.appendChild(b)})} buildInv();
// Minimal dependency-free 3D WebGL island. No CDN required, so it remains GitHub Pages friendly.
let gl,prog,buf,worldStarted=false,px=0,pz=0,yaw=0,keys={};
const vs=`attribute vec3 p;uniform mat4 mvp;varying vec3 v;void main(){v=p;gl_Position=mvp*vec4(p,1.0);}`;
const fs=`precision mediump float;varying vec3 v;void main(){float h=max(0.0,v.y);vec3 c=mix(vec3(.05,.16,.12),vec3(.55,.48,.28),smoothstep(0.0,3.0,h));if(v.y<0.1)c=vec3(.03,.19,.25);gl_FragColor=vec4(c,1.0);}`;
function matMul(a,b){let o=new Float32Array(16);for(let r=0;r<4;r++)for(let c=0;c<4;c++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function perspective(fov,asp,n,f){let t=1/Math.tan(fov/2),o=new Float32Array(16);o[0]=t/asp;o[5]=t;o[10]=(f+n)/(n-f);o[11]=-1;o[14]=2*f*n/(n-f);return o}
function lookAt(x,y,z,tx,ty,tz){let fx=tx-x,fy=ty-y,fz=tz-z;let fl=Math.hypot(fx,fy,fz);fx/=fl;fy/=fl;fz/=fl;let rx=fz,rz=-fx;let rl=Math.hypot(rx,rz);rx/=rl;rz/=rl;let ux=-rz*fy,uy=rz*fx- rx*fz,uz=rx*fy;return new Float32Array([rx,ux,-fx,0,0,uy,-fy,0,rz,uz,-fz,0,-(rx*x+rz*z),-(ux*x+uy*y+uz*z),fx*x+fy*y+fz*z,1])}
function startGame(){if(worldStarted)return;worldStarted=true;const c=$('world');gl=c.getContext('webgl',{antialias:true});if(!gl){$('status').textContent='WebGL unavailable';return} const v=gl.createShader(gl.VERTEX_SHADER);gl.shaderSource(v,vs);gl.compileShader(v);const f=gl.createShader(gl.FRAGMENT_SHADER);gl.shaderSource(f,fs);gl.compileShader(f);prog=gl.createProgram();gl.attachShader(prog,v);gl.attachShader(prog,f);gl.linkProgram(prog);buf=gl.createBuffer();const verts=[];for(let x=-30;x<30;x+=2)for(let z=-30;z<30;z+=2){let h=2*Math.sin(x*.16)*Math.cos(z*.14)+1;verts.push(x,h,z,x+2,h,z,x,h,z+2,x+2,h,z+2)}gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);addInput();requestAnimationFrame(loop)}
function addInput(){addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);let sx=0;document.addEventListener('pointerdown',e=>sx=e.clientX);document.addEventListener('pointermove',e=>{if(e.buttons){yaw+=(e.clientX-sx)*.004;sx=e.clientX}})}
function loop(){if(!worldStarted)return;let sp=.14;if(keys.w)px+=Math.sin(yaw)*sp,pz+=Math.cos(yaw)*sp;if(keys.s)px-=Math.sin(yaw)*sp,pz-=Math.cos(yaw)*sp;if(keys.a)px-=Math.cos(yaw)*sp,pz+=Math.sin(yaw)*sp;if(keys.d)px+=Math.cos(yaw)*sp,pz-=Math.sin(yaw)*sp;const c=$('world');c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;gl.viewport(0,0,c.width,c.height);gl.clearColor(.015,.03,.04,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.useProgram(prog);const p=perspective(1.05,c.width/c.height,.1,100),v=lookAt(px,5,pz,px+Math.sin(yaw),3,pz+Math.cos(yaw));gl.uniformMatrix4fv(gl.getUniformLocation(prog,'mvp'),false,matMul(p,v));gl.bindBuffer(gl.ARRAY_BUFFER,buf);const loc=gl.getAttribLocation(prog,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);gl.drawArrays(gl.TRIANGLE_STRIP,0, (30*30*4));$('coords').textContent=`X ${px.toFixed(0)} Z ${pz.toFixed(0)}`;requestAnimationFrame(loop)}
